#!/bin/bash


function usage {
	>&2 echo "Usage $0 [new|all]"
	exit 1
}


if [ $# -ne 1 ]; then
	usage
fi

argument=$1
folder=~/.recollect/
date=`date +"%Y-%m-%d"`
extension=".txt"
filename="${folder}entry-${date}${extension}"

case $argument in
new)
	# prompting
	echo "Entry: ${date}"
	echo "Press Ctrl+D to finish"
	echo


	# recording
	note=`cat`
	

	# saving
	mkdir -p $folder

	echo "Entry: ${date}" >> $filename
	echo >> $filename
	echo $note >> $filename
	echo >> $filename
	echo >> $filename
	;;
all)
	for entry in `ls ${folder}`; do
		cat "${folder}${entry}"
		echo
	done
	;;
clean)
	rm ${folder}*${extension}
	;;
*)
	usage
	;;
esac

